version: '3'
services:
  unison:
    build:
      context: ..
    environment:
      UNISON_DIR: /data
      UNISON_HOST_DIR: /host_data
    ports:
      # this will use a randomly assigned port
      - "5001"
    volumes:
      - unison:/data
      - ./test_files:/host_data
  reader:
    build:
      context: .
      dockerfile: Dockerfile.reader
    command: unison:5001 -s -t 30 -- cat /test_files/zzz.txt
    depends_on: [ unison ]
    volumes:
      - unison:/test_files
volumes:
  unison:
